### PR TITLE
Added option to disable a default plugin and disable all defaults

### PR DESCRIPTION
**Pull request by firyx**
Updated index.js and readme documentation.

### CODE REVIEW

**Comment by Gosha** [comment]
Documentation changes doesn't mention [`{disableDefaults: true}`](https://github.com/ahmadnassri/metalsmith-imagemin/pull/62/commits/e48ccafff2b45b08beed2485b9eff556909ca664#diff-6d186b954a58d5bb740f73d84fe39073R39)

**Comment by firyx** [comment]
Hi @Gosha,

Documentation changes don't mention `{disableDefaults: true}`

Because disabling default plugin is done the following way as described in README.txt:

To disable a default plugin use `pluginname: null`.

**Comment by ahmadnassri** [comment]
sorry for the delay in merging this ... about to release it now

**Comment by Gosha** [comment]
@firyx Yes that makes sense, but I don't see why there should be an option that isn't documented.

**Comment by firyx** [comment]
@Gosha 

If you want to disable a default plugin, please follow the existing documentation.

There is an option in code to disable default plugins.
It is documented in README and it is done this way:
`pluginname: null`

It is not possible to disable default plugin this way:
`{disableDefaults: true}`
this is not in code
and this is not in documentation.

**Comment by firyx** [comment]
@Gosha 

Hey Man,
sorry,
you are right!!!

I forgot to update documentation with `{disableDefaults: true}`.

Can you please update documentation and create a PR?

Thanks

**Comment by ahmadnassri** [comment]
docs updated :+1:

**Pull request merged**
